PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema$>
PREFIX lexinfo: <http://www.lexinfo.net/ontology/3.0/lexinfo#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#>
PREFIX lexis: <http://www.example.com/lexis/>

CONSTRUCT {
  ?map_uri conll:replace ?mapped .
  ?map_uri conll:replace ?mapped2
} WHERE {
  BIND(URI(?map) as ?map_uri)
  BIND(?GRAMCATEN as ?mapped)
  BIND(CONCAT(?GRAMCATEN, ' ', ?GRAMSUBCATEN) as ?mapped2)

}
