PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema$>
PREFIX lexinfo: <http://www.lexinfo.net/ontology/3.0/lexinfo#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#>
PREFIX lexis: <http://www.example.com/lexis/>

DELETE {
  ?entry lexinfo:partOfSpeech ?lexis_tag .
}
INSERT {
  ?entry lexinfo:partOfSpeech ?lexinfo_tag .
 }
WHERE {
  ?entry rdf:type ontolex:LexicalEntry .
  ?entry lexinfo:partOfSpeech ?lexis_tag .
  GRAPH <http://mapping> {
    ?lexinfo_tag conll:replace ?lexis_tag
  }
}
